Repository MadridSquad/Movio, pull requests merged in 2025-07, with the labels that each got.

#9 feature/app navigation
  gradle/libs.versions.toml
  presentation/build.gradle.kts
  presentation/src/main/java/com/example/presentation/component/BottomNavBar.kt
  presentation/src/main/java/com/example/presentation/navigation/AuthNavGraph.kt
  presentation/src/main/java/com/example/presentation/navigation/MovioNavGraph.kt
  presentation/src/main/java/com/example/presentation/navigation/Screen.kt
  presentation/src/main/java/com/example/presentation/navigation/route/ForgetPasswordRoute.kt
  presentation/src/main/java/com/example/presentation/navigation/route/HomeRoute.kt
  presentation/src/main/java/com/example/presentation/navigation/route/LibraryRoute.kt
  presentation/src/main/java/com/example/presentation/navigation/route/LoginRoute.kt
  presentation/src/main/java/com/example/presentation/navigation/route/MoreRoute.kt
  presentation/src/main/java/com/example/presentation/navigation/route/OnBoardingRoute.kt
  presentation/src/main/java/com/example/presentation/navigation/route/SearchRoute.kt
  presentation/src/main/java/com/example/presentation/navigation/route/SignUpRoute.kt
  presentation/src/main/java/com/example/presentation/navigation/route/SplashRoute.kt
  presentation/src/main/res/drawable/icon_home.xml
  presentation/src/main/res/drawable/icon_home_selected.xml
  presentation/src/main/res/drawable/icon_library.xml
  presentation/src/main/res/drawable/icon_library_selected.xml
  presentation/src/main/res/drawable/icon_more.xml
  presentation/src/main/res/drawable/icon_more_selected.xml
  presentation/src/main/res/drawable/icon_search.xml
  presentation/src/main/res/drawable/icon_search_selected.xml
  presentation/src/main/res/values-ar/string.xml
  presentation/src/main/res/values/string.xml
Labels: enhancement

#86 Refactor/detect image content
  app/src/main/java/com/madrid/movio/app.kt
  detectImageContent/build.gradle.kts
  detectImageContent/src/main/java/com/madrid/detectImageContent/FilteredImage.kt
  detectImageContent/src/main/java/com/madrid/detectImageContent/SensitiveContentDetection.kt
  presentation/src/main/java/com/madrid/presentation/composables/filteredImage/FilteredImage.kt
  presentation/src/main/java/com/madrid/presentation/composables/filteredImage/FilteredImageUiState.kt
  presentation/src/main/java/com/madrid/presentation/composables/filteredImage/FilteredImageViewModel.kt
Labels: bug

#295 Feature/movie series genres
  data/src/main/java/com/madrid/data/dataSource/local/mappers/GenreMappers.kt
  data/src/main/java/com/madrid/data/dataSource/remote/RemoteDataSourceImpl.kt
  data/src/main/java/com/madrid/data/dataSource/remote/dto/genre/GenresResponse.kt
  data/src/main/java/com/madrid/data/dataSource/remote/dto/movie/MovieDetailsResponse.kt
  data/src/main/java/com/madrid/data/dataSource/remote/mapper/GenreMapper.kt
  data/src/main/java/com/madrid/data/dataSource/remote/mapper/MovieMappers.kt
  data/src/main/java/com/madrid/data/repositories/MovieRepositoryImpl.kt
  data/src/main/java/com/madrid/data/repositories/SearchRepositoryImpl.kt
  data/src/main/java/com/madrid/data/repositories/SeriesRepositoryImpl.kt
  data/src/main/java/com/madrid/data/repositories/remote/RemoteDataSource.kt
  domain/src/main/java/com/madrid/domain/entity/Genre.kt
  domain/src/main/java/com/madrid/domain/repository/MovieRepository.kt
  domain/src/main/java/com/madrid/domain/repository/SeriesRepository.kt
  domain/src/main/java/com/madrid/domain/usecase/movie/GetMovieGenresUseCase.kt
  domain/src/main/java/com/madrid/domain/usecase/series/GetSeriesGenresUseCase.kt
Labels: feature

#328 Feature/home categories screen
  app/src/main/java/com/madrid/movio/di/DomainModule.kt
  data/src/main/java/com/madrid/data/dataSource/remote/MovieApi.kt
  data/src/main/java/com/madrid/data/dataSource/remote/RemoteDataSourceImpl.kt
  data/src/main/java/com/madrid/data/dataSource/remote/dto/series/RecommendedSeriesResponse.kt
  data/src/main/java/com/madrid/data/dataSource/remote/mapper/SeriesMappers.kt
  data/src/main/java/com/madrid/data/repositories/MovieRepositoryImpl.kt
  data/src/main/java/com/madrid/data/repositories/SeriesRepositoryImpl.kt
  data/src/main/java/com/madrid/data/repositories/getSortType.kt
  data/src/main/java/com/madrid/data/repositories/remote/RemoteDataSource.kt
  domain/src/main/java/com/madrid/domain/entity/SortType.kt
  domain/src/main/java/com/madrid/domain/repository/MovieRepository.kt
  domain/src/main/java/com/madrid/domain/repository/SeriesRepository.kt
  domain/src/main/java/com/madrid/domain/usecase/movie/GetMovieDetailsUseCase.kt
  domain/src/main/java/com/madrid/domain/usecase/movie/GetMoviesByGenreIdUseCase.kt
  domain/src/main/java/com/madrid/domain/usecase/search/GetMoviesByQueryUseCase.kt
  domain/src/main/java/com/madrid/domain/usecase/series/GetSeriesByGenreIdUseCase.kt
  presentation/src/main/java/com/madrid/presentation/component/CustomHorizontalCard.kt
  presentation/src/main/java/com/madrid/presentation/component/MovioPager.kt
  presentation/src/main/java/com/madrid/presentation/screens/homeScreen/HomeScreen.kt
  presentation/src/main/java/com/madrid/presentation/screens/homeScreen/component/TrendingLayout.kt
  presentation/src/main/java/com/madrid/presentation/screens/homeScreen/layout/AllMediaLayout.kt
  presentation/src/main/java/com/madrid/presentation/screens/homeScreen/layout/CategoriesLayout.kt
  presentation/src/main/java/com/madrid/presentation/screens/searchScreen/SeeAllForYou/SeeAllForYouViewModel.kt
  presentation/src/main/java/com/madrid/presentation/screens/searchScreen/paging/BasePagingSource.kt
  presentation/src/main/java/com/madrid/presentation/screens/searchScreen/paging/ExplorePagingSource.kt
  presentation/src/main/java/com/madrid/presentation/screens/searchScreen/paging/ForYouPagingSource.kt
  presentation/src/main/java/com/madrid/presentation/screens/searchScreen/paging/SearchArtistPagingSource.kt
  presentation/src/main/java/com/madrid/presentation/screens/searchScreen/paging/SearchMoviePagingSource.kt
  presentation/src/main/java/com/madrid/presentation/screens/searchScreen/paging/SearchSeriesPagingSource.kt
  presentation/src/main/java/com/madrid/presentation/viewModel/base/BaseViewModel.kt
  presentation/src/main/java/com/madrid/presentation/viewModel/detailsViewModel/DetailsMovieViewModel.kt
  presentation/src/main/java/com/madrid/presentation/viewModel/homeViewModel/HomeCategoriesPagingSource.kt
  presentation/src/main/java/com/madrid/presentation/viewModel/homeViewModel/HomeInteractionListener.kt
  presentation/src/main/java/com/madrid/presentation/viewModel/homeViewModel/HomeScreenEffect.kt
  presentation/src/main/java/com/madrid/presentation/viewModel/homeViewModel/HomeScreenState.kt
  presentation/src/main/java/com/madrid/presentation/viewModel/homeViewModel/HomeViewModel.kt
  presentation/src/main/java/com/madrid/presentation/viewModel/homeViewModel/Mapper.kt
  presentation/src/main/java/com/madrid/presentation/viewModel/homeViewModel/TrendingUiState.kt
  presentation/src/main/java/com/madrid/presentation/viewModel/searchViewModel/SearchScreenState.kt
  presentation/src/main/java/com/madrid/presentation/viewModel/searchViewModel/SearchViewModel.kt
  presentation/src/main/java/com/madrid/presentation/viewModel/shared/MediaUiState.kt
  presentation/src/main/java/com/madrid/presentation/viewModel/uiStateMapper/UiStateMapper.kt
Labels: feature
