Repository MadridSquad/Movio, pull requests merged in 2025-08, with the labels that each got.

#351 Refactor/data store
  app/src/main/java/com/madrid/movio/di/DataModule.kt
  data/src/main/java/com/madrid/data/dataSource/datastore/Crypto.kt
  data/src/main/java/com/madrid/data/dataSource/datastore/UserData.kt
  data/src/main/java/com/madrid/data/dataSource/datastore/UserPreferencesImpl.kt
  data/src/main/java/com/madrid/data/repositories/UserRepositoryImpl.kt
  data/src/main/java/com/madrid/data/repositories/datasource/UserPreferences.kt
Labels: refactor

#381 feature/theme-language
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/madrid/movio/di/hilt/RepositoryModule.kt
  app/src/main/res/xml/locales_config.xml
  data/src/main/java/com/madrid/data/dataSource/datastore/UserPreferencesImpl.kt
  data/src/main/java/com/madrid/data/repositories/AuthenticationRepositoryImpl.kt
  data/src/main/java/com/madrid/data/repositories/MovieRepositoryImpl.kt
  data/src/main/java/com/madrid/data/repositories/PreferencesRepositoryImpl.kt
  data/src/main/java/com/madrid/data/repositories/SeriesRepositoryImpl.kt
  data/src/main/java/com/madrid/data/repositories/datasource/UserPreferences.kt
  data/src/main/java/com/madrid/data/repositories/mapper/LanguageMapper.kt
  data/src/main/java/com/madrid/data/repositories/mapper/ThemeMapper.kt
  designSystem/src/main/java/com/madrid/designSystem/component/SettingsItem.kt
  designSystem/src/main/java/com/madrid/designSystem/component/ShareBottomSheet.kt
  designSystem/src/main/res/values-ar/strings.xml
  designSystem/src/main/res/values/strings.xml
  domain/src/main/java/com/madrid/domain/repository/AuthenticationRepository.kt
  domain/src/main/java/com/madrid/domain/repository/PreferencesRepository.kt
  domain/src/main/java/com/madrid/domain/usecase/authentication/CheckFirstLaunchUseCase.kt
  domain/src/main/java/com/madrid/domain/usecase/authentication/GetCurrentUserDetailsUseCase.kt
  domain/src/main/java/com/madrid/domain/usecase/authentication/LoginUseCase.kt
  domain/src/main/java/com/madrid/domain/usecase/authentication/LogoutUseCase.kt
  domain/src/main/java/com/madrid/domain/usecase/movie/GetUserRatedMovieUseCase.kt
  domain/src/main/java/com/madrid/domain/usecase/preferences/GetAppThemeUseCase.kt
  domain/src/main/java/com/madrid/domain/usecase/preferences/GetLanguageUseCase.kt
  domain/src/main/java/com/madrid/domain/usecase/preferences/SetAppThemeUseCase.kt
  domain/src/main/java/com/madrid/domain/usecase/preferences/SetLanguageUseCase.kt
  domain/src/main/java/com/madrid/domain/usecase/series/GetUserRatedSeriesUseCase.kt
  domain/src/main/java/com/madrid/domain/utils/AppLanguage.kt
  domain/src/main/java/com/madrid/domain/utils/AppTheme.kt
  presentation/build.gradle.kts
  presentation/src/main/java/com/madrid/presentation/MainActivity.kt
  presentation/src/main/java/com/madrid/presentation/screens/moreScreen/MoreScreen.kt
  presentation/src/main/java/com/madrid/presentation/screens/moreScreen/component/SelectionBottomSheet.kt
  presentation/src/main/java/com/madrid/presentation/utils/Language.kt
  presentation/src/main/java/com/madrid/presentation/viewModel/authentication/MainViewModel.kt
  presentation/src/main/java/com/madrid/presentation/viewModel/moreViewModel/Mapper.kt
  presentation/src/main/java/com/madrid/presentation/viewModel/moreViewModel/MoreInteractionListener.kt
  presentation/src/main/java/com/madrid/presentation/viewModel/moreViewModel/MoreUiState.kt
  presentation/src/main/java/com/madrid/presentation/viewModel/moreViewModel/MoreViewModel.kt
  presentation/src/main/res/values-ar/strings.xml
  presentation/src/main/res/values/strings.xml
Labels: feature

#400 Feature/implement play functionality
  presentation/src/main/java/com/madrid/presentation/screens/detailsScreen/detailsMovieScreen/MovieDetailScreen.kt
  presentation/src/main/java/com/madrid/presentation/screens/detailsScreen/seriesDetails/SeriesDetailsScreen.kt
  presentation/src/main/java/com/madrid/presentation/viewModel/detailsViewModel/DetailsMovieUiState.kt
  presentation/src/main/java/com/madrid/presentation/viewModel/detailsViewModel/DetailsMovieViewModel.kt
  presentation/src/main/java/com/madrid/presentation/viewModel/detailsViewModel/SeriesDetailsUiState.kt
  presentation/src/main/java/com/madrid/presentation/viewModel/detailsViewModel/SeriesDetailsViewModel.kt
Labels: feature

#432 Fix/add to favorite
  data/src/main/java/com/madrid/data/dataSource/remote/RemoteDataSourceImpl.kt
  data/src/main/java/com/madrid/data/repositories/MovieRepositoryImpl.kt
  data/src/main/java/com/madrid/data/repositories/SeriesRepositoryImpl.kt
  data/src/main/java/com/madrid/data/repositories/remote/RemoteDataSource.kt
  designSystem/src/main/java/com/madrid/designSystem/component/TopAppBar.kt
  domain/src/main/java/com/madrid/domain/repository/MovieRepository.kt
  domain/src/main/java/com/madrid/domain/repository/SeriesRepository.kt
  domain/src/main/java/com/madrid/domain/usecase/movie/SetMovieFavoriteStatusUseCase.kt
  domain/src/main/java/com/madrid/domain/usecase/series/SetSeriesFavoriteStatusUseCase.kt
  presentation/src/main/java/com/madrid/presentation/viewModel/detailsViewModel/DetailsMovieViewModel.kt
  presentation/src/main/java/com/madrid/presentation/viewModel/detailsViewModel/SeriesDetailsViewModel.kt
Labels: bug

#482 Feature/delete from list
  data/src/main/java/com/madrid/data/dataSource/remote/MovioApi.kt
  data/src/main/java/com/madrid/data/dataSource/remote/RemoteDataSourceImpl.kt
  data/src/main/java/com/madrid/data/dataSource/remote/dto/list/RemoveMovieDto.kt
  data/src/main/java/com/madrid/data/repositories/MovieRepositoryImpl.kt
  data/src/main/java/com/madrid/data/repositories/remote/RemoteDataSource.kt
  designSystem/src/main/java/com/madrid/designSystem/component/DialogWithButtonLayout.kt
  domain/src/main/java/com/madrid/domain/repository/MovieRepository.kt
  domain/src/main/java/com/madrid/domain/usecase/movie/RemoveMovieFromListUseCase.kt
  presentation/src/main/java/com/madrid/presentation/navigation/MovioNavHost.kt
  presentation/src/main/java/com/madrid/presentation/screens/addtolist/SuccessNotificationRow.kt
  presentation/src/main/java/com/madrid/presentation/screens/libraryScreen/layout/WatchListDetailsScreen.kt
  presentation/src/main/java/com/madrid/presentation/screens/libraryScreen/watchList/WatchListDetailsScreen.kt
  presentation/src/main/java/com/madrid/presentation/viewModel/libraryViewModel/layout/WatchListDetailsEffect.kt
  presentation/src/main/java/com/madrid/presentation/viewModel/libraryViewModel/layout/WatchListDetailsInteractionListener.kt
  presentation/src/main/java/com/madrid/presentation/viewModel/libraryViewModel/layout/WatchListDetailsViewModel.kt
  presentation/src/main/java/com/madrid/presentation/viewModel/libraryViewModel/layout/WatchListState.kt
  presentation/src/main/res/drawable/empty_list.xml
  presentation/src/main/res/values-ar/strings.xml
  presentation/src/main/res/values/strings.xml
Labels: feature

#522 Adds validation to prevent users from submitting movie ratings without selecting any stars
  presentation/src/main/java/com/madrid/presentation/screens/detailsScreen/detailsMovieScreen/MovieDetailScreen.kt
  presentation/src/main/java/com/madrid/presentation/viewModel/detailsViewModel/DetailsMovieViewModel.kt
Labels: enhancement

#539 fix: Restore navigation bars padding in MovioNavGraph
  presentation/src/main/java/com/madrid/presentation/navigation/MovioNavGraph.kt
Labels: enhancement

#548 fix: loading data when navigate back to library screen
  presentation/src/main/java/com/madrid/presentation/screens/libraryScreen/LibraryScreen.kt
  presentation/src/main/java/com/madrid/presentation/screens/libraryScreen/ViewAllScreen.kt
  presentation/src/main/java/com/madrid/presentation/screens/libraryScreen/WatchlistViewAllScreen.kt
  presentation/src/main/java/com/madrid/presentation/viewModel/libraryViewModel/LibraryViewModel.kt
Labels: bug

#549 Refactor/series details code
  domain/src/main/java/com/madrid/domain/usecase/series/AddSeriesToHistoryUseCase.kt
  presentation/src/main/java/com/madrid/presentation/component/TopCastHorizontalScroll.kt
  presentation/src/main/java/com/madrid/presentation/screens/detailsScreen/movieDetail/MovieDetail.kt
  presentation/src/main/java/com/madrid/presentation/screens/detailsScreen/reviewsScreen/composables/ReviewsSection.kt
  presentation/src/main/java/com/madrid/presentation/screens/detailsScreen/seriesDetails/EpisodesScreen.kt
  presentation/src/main/java/com/madrid/presentation/screens/detailsScreen/seriesDetails/SeasonsScreen.kt
  presentation/src/main/java/com/madrid/presentation/screens/detailsScreen/seriesDetails/SeriesDetailsScreen.kt
  presentation/src/main/java/com/madrid/presentation/screens/detailsScreen/seriesDetails/component/AddRatingBottomSheet.kt
  presentation/src/main/java/com/madrid/presentation/screens/detailsScreen/seriesDetails/component/CurrentSeasonsSection.kt
  presentation/src/main/java/com/madrid/presentation/screens/detailsScreen/seriesDetails/component/DescriptionSection.kt
  presentation/src/main/java/com/madrid/presentation/screens/detailsScreen/seriesDetails/component/DoneAddRating.kt
  presentation/src/main/java/com/madrid/presentation/screens/detailsScreen/seriesDetails/component/ShareBottomSheet.kt
  presentation/src/main/java/com/madrid/presentation/screens/detailsScreen/seriesDetails/component/SimilarSeriesHorizontalSection.kt
  presentation/src/main/java/com/madrid/presentation/screens/detailsScreen/seriesDetails/component/TopCastSection.kt
  presentation/src/main/java/com/madrid/presentation/screens/detailsScreen/similarMedia/SimilarSeriesScreen.kt
  presentation/src/main/java/com/madrid/presentation/utils/CopyToClipboard.kt
  presentation/src/main/java/com/madrid/presentation/utils/PlayTrailer.kt
  presentation/src/main/java/com/madrid/presentation/utils/ShareToApp.kt
  presentation/src/main/java/com/madrid/presentation/viewModel/detailsViewModel/DetailsMovieUiState.kt
  presentation/src/main/java/com/madrid/presentation/viewModel/detailsViewModel/ReviewsScreenUiState.kt
  presentation/src/main/java/com/madrid/presentation/viewModel/detailsViewModel/ReviewsScreenViewModel.kt
  presentation/src/main/java/com/madrid/presentation/viewModel/detailsViewModel/SeriesDetails/SeriesDetailsEffect.kt
  presentation/src/main/java/com/madrid/presentation/viewModel/detailsViewModel/SeriesDetails/SeriesDetailsInteractionListener.kt
  presentation/src/main/java/com/madrid/presentation/viewModel/detailsViewModel/SeriesDetails/SeriesDetailsMappers.kt
  presentation/src/main/java/com/madrid/presentation/viewModel/detailsViewModel/SeriesDetails/SeriesDetailsUiState.kt
  presentation/src/main/java/com/madrid/presentation/viewModel/detailsViewModel/SeriesDetails/SeriesDetailsViewModel.kt
  presentation/src/main/java/com/madrid/presentation/viewModel/detailsViewModel/SeriesDetailsMappers.kt
  presentation/src/main/java/com/madrid/presentation/viewModel/detailsViewModel/SeriesDetailsViewModel.kt
  presentation/src/main/res/values-ar/strings.xml
  presentation/src/main/res/values/strings.xml
Labels: enhancement

#560 refactor: season poster , number of seasons in episodes screen dropdown
  presentation/src/main/java/com/madrid/presentation/screens/detailsScreen/seriesDetails/EpisodesScreen.kt
  presentation/src/main/java/com/madrid/presentation/screens/detailsScreen/seriesDetails/SeriesDetailsScreen.kt
  presentation/src/main/java/com/madrid/presentation/screens/detailsScreen/seriesDetails/component/CurrentSeasonsSection.kt
  presentation/src/main/java/com/madrid/presentation/viewModel/detailsViewModel/SeriesDetails/SeriesDetailsViewModel.kt
Labels: documentation, help wanted

#584 Fix/padding spacing
  presentation/src/main/java/com/madrid/presentation/component/TopCastHorizontalScroll.kt
  presentation/src/main/java/com/madrid/presentation/screens/detailsScreen/castDetails/TopCastDetailsScreen.kt
  presentation/src/main/java/com/madrid/presentation/screens/detailsScreen/movieDetail/MovieDetail.kt
  presentation/src/main/java/com/madrid/presentation/screens/detailsScreen/seriesDetails/SeriesDetailsScreen.kt
  presentation/src/main/java/com/madrid/presentation/screens/detailsScreen/seriesDetails/component/SimilarSeriesHorizontalSection.kt
  presentation/src/main/java/com/madrid/presentation/screens/detailsScreen/similarMedia/SeeAllSimilarMediaScreen.kt
  presentation/src/main/java/com/madrid/presentation/screens/homeScreen/SeeAllMoviesScreen.kt
  presentation/src/main/java/com/madrid/presentation/screens/homeScreen/SeeAllTVShowsScreen.kt
  presentation/src/main/java/com/madrid/presentation/screens/homeScreen/component/TrendingLayout.kt
  presentation/src/main/java/com/madrid/presentation/screens/loginScreen/LoginScreen.kt
  presentation/src/main/java/com/madrid/presentation/screens/moreScreen/component/SelectionBottomSheet.kt
  presentation/src/main/java/com/madrid/presentation/screens/onboarding/OnBoardingScreen.kt
  presentation/src/main/java/com/madrid/presentation/screens/searchScreen/features/recentSearchLayout/FilterSearchScreen.kt
  presentation/src/main/java/com/madrid/presentation/screens/searchScreen/features/recentSearchLayout/ForYouAndExploreScreen.kt
  presentation/src/main/java/com/madrid/presentation/screens/searchScreen/seeAllForYou/SeeAllForYouScreen.kt
Labels: bug
